import type { Metadata } from "next";
import { Alata, Josefin_Sans } from "next/font/google";
import { twMerge } from "tailwind-merge";
import { Header } from "@/components/Header/Header";
import "@/app/globals.css";

export const alata = Alata({
  subsets: ["latin"],
  variable: "--alata",
  weight: ["400"],
});

export const josefinSans = Josefin_Sans({
  subsets: ["latin"],
  variable: "--josefin-sans",
  weight: ["300", "400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body
      className={twMerge(
        "sm:grid sm:grid-cols-1 sm:grid-rows-[auto_1fr_auto] sm:min-h-screen sm:w-full",
        alata.variable,
        josefinSans.variable,
      )}
    >
      <Header />

      {children}
    </body>
  </html>
);

export default RootLayout;
