import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import { Header } from "@/components/Header/Header";
import "@/app/globals.css";

const josefinSans = Josefin_Sans({
  subsets: ["latin"],
  variable: "--josefin-sans",
  weight: ['300']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children
}: { children: React.ReactNode }) => (
  <html lang="en">
    <body className="sm:grid sm:grid-cols-1 sm:grid-rows-[auto_1fr_auto] sm:min-h-screen sm:w-full">
      <Header />

      {children}
    </body>
  </html>
);

export default RootLayout;